rootNamespace: "default"
registryAuth:
  use: false
  token: ""
ingress:
  use: true
  certManager: true
  host: "localhost"
backend:
  imageURL: "localhost:32000/backend:registry"
  env:
    BUILD_TYPE: "development"
    REDIS_URL: 'redis://redis-service.default.svc.cluster.local:6379'
    EMPHIRIAL: "1"
    DJ_DEBUG: "1"
    DJ_SECRET_KEY: "bla bla"
    DJ_ALLOWED_HOSTS: "*"
    DJ_TIME_ZONE: "UTC"
    DJ_CELERY_TIMEZONE: Australia/Tasmania
    DJ_MANAGEMENT_USER_MAIL: admin@user.com
    DJ_MANAGEMENT_PW: Admin123!
    DJ_ADMIN_OPEN_KEYPHRASE: opensesame
    DJ_USE_MINIO: "0"
    DJ_MINIO_ROOT_USER: ""
    DJ_MINIO_ROOT_PASSWORD: ""
    DJ_MINIO_BUCKET_NAME: ""
    DJ_MINIO_MEDIA_BUCKET_NAME: ""
    DJ_MINIO_ENDPOINT: ""
    DJ_TWILIO_ACCOUNT_SID: AccSidNotProvidedInDev
    DJ_TWILIO_API_KEY_SID: TwApiKeyNotIncludedDev
    DJ_TWILIO_API_SECRET: TwApiSecretNotIncludedDev
    FR_FRONTENDS: user_form_frontend,main_frontend,cookie_banner_frontend,admin_panel_frontend,user_form
    WEBPACK_PUBLIC_PATH: ""
    WEBPACK_DEV_TOOL: "eval-cheap-module-source-map"
    WEBPACK_DEBUG: "1"
    DJ_SG_SENDGRID_API_KEY: "not_an_api_key"
    DJ_SG_DEFAULT_FROM_EMAIL: "admin@user.com"
    DJ_BASE_URL: http://localhost
    DJ_TIM_MANAGEMENT_PW: "Test123!"
    DJ_CALCOM_QUERY_ACCESS_PARAM: "secret"
    DJ_CALCOM_MEETING_ID: "herr-duenschnlate-iiscv9/15min"
    DJ_USE_SENTRY: "0"
    DJ_SENTRY_DNS: ""

