rootNamespace: "default"
patenmatch:
  use: false
  imageUrl: ""
registryAuth:
  use: false
  host: "ghcr.io"
  token: ""
ingress:
  use: true
  certManager: true
  host: "patenmatch.de"
docs:
  use: false
  replicas: 1
  imageURL: "localhost:32000/docs:registry"
  env:
    DJ_DOCS_BUILD: "1"
    USE_WHITENOISE: "1"
    PUBLIC_FRONTEND_PATH: ""
    BUILD_TYPE: "development"
    DJ_SECRET_KEY: "none"
    DJ_DEBUG: "0"
    FR_FRONTENDS: ""
    DJ_MANAGEMENT_USER_MAIL: ""
    DJ_ADMIN_OPEN_KEYPHRASE: ""
    DJ_SG_DEFAULT_FROM_EMAIL: ""
    DJ_TWILIO_ACCOUNT_SID: ""
    DJ_TWILIO_API_KEY_SID: ""
    DJ_TWILIO_API_SECRET: ""
    DJ_CELERY_TIMEZONE: "Australia/Tasmania"
    DJ_TIME_ZONE: "UTC"
backend:
  replicas: 1
  imageURL: "localhost:32000/backend:registry"
  env:
    BUILD_TYPE: "development"
    REDIS_URL: "redis://redis-service.default.svc.cluster.local:6379"
    EMPHIRIAL: "1"
    DJ_DOCS_PROXY: "0"
    DJ_DOCS_URL: ""
    DJ_DEBUG: "1"
    DJ_SECRET_KEY: "bla bla"
    DJ_ALLOWED_HOSTS: "*"
    DJ_TIME_ZONE: "UTC"
    DJ_CELERY_TIMEZONE: Australia/Tasmania
    DJ_MANAGEMENT_USER_MAIL: admin@user.com
    DJ_MANAGEMENT_PW: Admin123!
    DJ_ADMIN_OPEN_KEYPHRASE: opensesame
    DJ_USE_MINIO: "0"
    DJ_MINIO_ROOT_USER: ""
    DJ_MINIO_ROOT_PASSWORD: ""
    DJ_MINIO_BUCKET_NAME: ""
    DJ_MINIO_MEDIA_BUCKET_NAME: ""
    DJ_MINIO_ENDPOINT: ""
    DJ_TWILIO_ACCOUNT_SID: AccSidNotProvidedInDev
    DJ_TWILIO_API_KEY_SID: TwApiKeyNotIncludedDev
    DJ_TWILIO_API_SECRET: TwApiSecretNotIncludedDev
    FR_FRONTENDS: main_frontend,cookie_banner_frontend,admin_panel_frontend
    WEBPACK_PUBLIC_PATH: ""
    WEBPACK_DEV_TOOL: "eval-cheap-module-source-map"
    WEBPACK_DEBUG: "1"
    DJ_SG_SENDGRID_API_KEY: "not_an_api_key"
    DJ_SG_DEFAULT_FROM_EMAIL: "admin@user.com"
    DJ_BASE_URL: http://localhost
    DJ_TIM_MANAGEMENT_PW: "Test123!"
    DJ_CALCOM_QUERY_ACCESS_PARAM: "secret"
    DJ_CALCOM_MEETING_ID: "herr-duenschnlate-iiscv9/15min"
    DJ_USE_SENTRY: "0"
    DJ_SENTRY_DNS: ""
