name: Build Android App
    
on:
  workflow_dispatch:
    inputs:
      COMMIT_REF:
        type: string
        description: commit ref
        default: 'master'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_android_app:
    runs-on: ubuntu-latest
    name: Build Android App
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.BOT_PAT }}
          submodules: recursive
          ref: "${{ github.event.inputs.COMMIT_REF }}"
      - name: Build Android App
        run: |
          cp front/env_apps/main_frontend.capacitor-dev.env.js front/apps/main_frontend/src/ENVIRONMENT.js
          docker pull ghcr.io/tbscode/tims-packages_capacitor_android:latest
          docker tag ghcr.io/tbscode/tims-packages_capacitor_android:latest android-capacitor
          docker compose -f docker-compose.capacitor-dev.yaml build android
          export APK_NAME="app-$(date +%s)-${{ github.event.inputs.COMMIT_REF }}.apk"
          docker ps -a
          mkdir -p ./front/apps/main_frontend/android-builds
          docker compose -f docker-compose.capacitor-dev.yaml run android
          cp front/apps/main_frontend/android-builds/latest.apk $APK_NAME
          echo "APK_NAME=$APK_NAME" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: Android Apk
          path: ${{ steps.build_android_app.outputs.APK_NAME }}
